### ISSUE TITLE
Contact name display fix

### ISSUE THREAD

**Issue by fr-Pursuit** [CamxxCore/iFruitContacts#11]
Hi.

I'm working on a mod that, amongst other things, takes full control of the phone, and I used some of your code to help me understand how to phone works.

By looking at the iFruit source code, I've found this:

```
if(this.dataProviderUI[_loc2_][3].substr(0,5) != "CHAR_" || this.dataProviderUI[_loc2_][3] == "CHAR_HUMANDEFAULT")
               {
                  this.container[_loc4_].contactNameMCcond.textAutoSize = "shrink";
                  this.container[_loc4_].contactNameMCcond.text = _loc5_;
               }
```

And, after testing, I can say that using uppercase texture names instead of lowercase ones indeed fixes the display difference between vanilla contacts and added contacts.

**Comment by fr-Pursuit** [comment]
Also, I put "STRING" instead of "CELL_2000"

**Comment by CamxxCore** [comment]
Quite interesting. Thanks for the info.

**Comment by fr-Pursuit** [comment]
No problem ! Just note that, as the code suggests, the fix only works when using icons that start with "CHAR_", so the issue will still be there when using  "DIA" icons. That's because DIA icons are only supposed to be used in the pause menu, in the section that recapitulates dialogs.

I close the issue as you got the info ^^
