### ISSUE TITLE
Script seems to not even start

### ISSUE THREAD

**Issue by mattszymanko** [CamxxCore/iFruitContacts#13]
I have installed ifruitaddon and ifruitaddon2. They've both seemed to work previously. But now when I installed them again they're not even working. Not creating any contacts.

**Comment by CamxxCore** [comment]
sorry I wish I could say I am actively supporting this project but its been many years. I suggest to speak to the creator of the ifruitaddon2 since I know he uses the script in a lot of his own mods (I'm Not MentaL)

**Comment by lopazgaming** [comment]
Hi. Thanks for replying. Problem got solved, idk how but is solved now. Thanks for contact anyway!
