### ISSUE TITLE
Move to SHVDN3

### ISSUE THREAD

**Issue by Michael21107** [CamxxCore/iFruitContacts#14]
@CamxxCore please move to SHVDN3 or let someone else manage this repo, kagkin (maintainer of SHVDN) for example

**Comment by BoBoBaSs84** [comment]
@Michael21107 Could you be that kind and test [this](https://github.com/BoBoBaSs84/iFruitAddon/releases/tag/v3.0.7.441) one?

**Comment by Michael21107** [comment]
how should i test it? the original is called iFruitAddon**2**, would scripts even be able to load it?

**Comment by BoBoBaSs84** [comment]
@Michael21107: Like testing it, by writing a script with it. ;)

![image](https://github.com/CamxxCore/iFruitAddon/assets/73112377/007d85da-50c5-4f6f-9734-0c912b20f4ac)

The assembly within the zip file uses `SHVDN3 (3.6.0)`.

![image](https://github.com/CamxxCore/iFruitAddon/assets/73112377/8c233794-1946-431f-be0a-98faee9ac109)

If you already have a mod that uses the `iFruitAddon` it should also work with this assembly and `SHVDN3`.

![image](https://github.com/CamxxCore/iFruitAddon/assets/73112377/317d2090-26cd-438e-ac35-8080bffed129)

**Comment by Michael21107** [comment]
i will test already existing script since i cant code shit 🤣

**Comment by Michael21107** [comment]
should it work with the nightly shvdn version?

**Comment by Michael21107** [comment]
so i deleted ifruitaddon2.dll, installed the 3 new ones, and [EAI](https://www.gta5-mods.com/scripts/enable-all-interiors-wip) apparently crashed due to it
[ScriptHookVDotNet.log](https://github.com/CamxxCore/iFruitAddon/files/14897996/ScriptHookVDotNet.log)
[ScriptHookV.log](https://github.com/CamxxCore/iFruitAddon/files/14897997/ScriptHookV.log)
[asiloader.log](https://github.com/CamxxCore/iFruitAddon/files/14897998/asiloader.log)

**Comment by BoBoBaSs84** [comment]
I'm going to have a close look on the logs tomorrow, thanks for looking things up!

**Comment by Michael21107** [comment]
yep, happy that someone decided to update it

**Comment by Michael21107** [comment]
@BoBoBaSs84 any chance you could allow issues on your repo?

**Comment by CamxxCore** [comment]
Hello guys. Sorry for the long reply. If someone has updated the project for SHVDN3 please feel free to submit a pull request.

**Comment by CamxxCore** [comment]
@BoBoBaSs84 would you be willing to sync your fork upstream to the main repo? Thanks 😊

**Comment by BoBoBaSs84** [comment]
Yeah, can do that.

**Comment by Michael21107** [comment]
@BoBoBaSs84 any chance you could allow issues on your repo?
