### ISSUE TITLE
Update the sample script please

### ISSUE THREAD

**Issue by RainerHilmer** [CamxxCore/iFruitContacts#2]
The Update method needs a handle now. What handle? Also, are there any other changes which a user of your framework should know of?

**Comment by CamxxCore** [comment]
Yes that method wasn't meant to be exposed, thanks. Fixed it now. The only Update() method you need to worry about is in the CustomiFruit class. The example has also been updated so that should give you some direction.

**Comment by RainerHilmer** [comment]
Thanks again. :)
