### ISSUE TITLE
Example script unclear

### ISSUE THREAD

**Issue by RainerHilmer** [CamxxCore/iFruitContacts#3]
Hi, it's me again. :)
I look at your example script and I don't quite understand what's the difference between the Selected event and the Answered event. In your example you attached the Contact_Answered method to the Answered event and that method has an iFruitContact parameter but that's not used in any way. This method just wraps another method (SpawnVehicle) and calls UI.Notify, which could also be in SpawnVehicle.

**Comment by CamxxCore** [comment]
Most methods have some sort of documentation if you go through the source. The example with the Answered event just defines the event handler with its parameters. The ifruitcontact passed to that method is the contact that answered the call. You could just as easily use lambda if you don't need to worry about the parameters.

**Comment by RainerHilmer** [comment]
So in a nutshell I only use the Answered event if I want to do any further actions on the contact, right? Thank you.

**Comment by CamxxCore** [comment]
Ya the selected event should probably be deprecated now seeing as the same effect can be achieved using the Answered event and setting DialTimeout = 0. I can see how that might have been confusing.
