### ISSUE TITLE
Typo on line 81 of ContactIcon.cs

### ISSUE THREAD

**Issue by ghost** [CamxxCore/iFruitContacts#6]
Hello, small issue I noticed was that on ContactIcon.cs line 81 
`public static ContactIcon Lester { get { return new ContactIcon("char_lazlow"); } }`

Basically it will show the icon for Lazlow if you select Lester. Just a minor issue.

Note: I'm very new to C# so I may be dead wrong and that may be intended, if I am please just correct me, thanks!

**Comment by CamxxCore** [comment]
Good eye. Thanks for letting me know.

**Comment by ghost** [comment]
No problem, happy to see the quick response!
